image: conanio/gcc8

stages:
  - build
  - test
  - deploy

before_script:
  - echo "Before script action"

build:
  tags:
    - kubernetes
  stage: build
  only:
    - master
  script:
    - ./build.sh
  artifacts:
    paths:
      - build/

test:
  tags:
    - kubernetes
  stage: test
  needs:
    - job: build
      artifacts: true
  script:
    - cd build/bin && ./GoogleTests --gtest_output=xml:report.xml
  artifacts:
    reports:
      junit: report.xml
