variables:
  X86_DOCKER_IMAGE: conanio/gcc8
  X86_64_DOCKER_IMAGE: registry.gear.ge.com/cbt/gcc8-with-coverity:0.2.0
  ARMV7_DOCKER_IMAGE: conanio/gcc8-armv7

.build:
  image: conanio/gcc8
  tags:
    - kubernetes
  stage: build
  script:
    - sudo chmod +x *.sh
    - ./build.sh $CONAN_PROFILE
  artifacts:
    paths:
      - build/

.test:
  image: conanio/gcc8
  tags:
    - kubernetes
  stage: test
  script:
    - cd build/bin && ./GoogleTests --gtest_output=xml:report.xml
  artifacts:
    reports:
      junit: build/bin/report.xml

stages:
  - build
  - test
  - deploy

build_x64:
  extends: .build 
  image: $X86_DOCKER_IMAGE

test:
  extends: .test 
  image: $X86_DOCKER_IMAGE
  
