variables:
  X86_DOCKER_IMAGE: conanio/gcc8
  X86_64_DOCKER_IMAGE: conanio/gcc8
  ARMV7_DOCKER_IMAGE: conanio/gcc8-armv7
  X86_CONAN_PROFILE: profiles/x86
  X86_64_CONAN_PROFILE: profiles/x86_64
  ARMV7_CONAN_PROFILE: profiles/armv7
  ARMV7_RUNTIME_DOCKER_IMAGE: arm32v7/debian 

.build:
  image: conanio/gcc8
  tags:
    - kubernetes
  stage: build
  script:
    - sudo chmod +x *.sh
    - ./build.sh $CONAN_PROFILE
  artifacts:
    paths:
      - build/

.test:
  image: conanio/gcc8
  tags:
    - kubernetes
  stage: test
  script:
    - cd build/bin && ./GoogleTests --gtest_output=xml:report.xml
  artifacts:
    reports:
      junit: build/bin/report.xml

stages:
  - build
  - test
  - deploy

x64:build:
  extends: .build
  variables:
    - CONAN_PROFILE: $X86_64_CONAN_PROFILE 
  image: $X86_64_DOCKER_IMAGE

x64:test:
  extends: .test 
  needs: ["x64:build"]
  image: $X86_64_DOCKER_IMAGE

armv7:build:
  extends: .build
  variables:
    - CONAN_PROFILE: $ARMV7_CONAN_PROFILE  
  image: $ARMV7_DOCKER_IMAGE

armv7:test:
  extends: .test
  needs: ["armv7:build"]
  image: $ARMV7_RUNTIME_DOCKER_IMAGE
  
