# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
    
  build:
    stage: "build"
    commands:
      - ./build.sh
    scale:
      x86_64:
        image: conanio/gcc8
        environment:
          - PROFILE="profiles/x86_64"
      x86:
        image: conanio/gcc8
        environment:
          - PROFILE="profiles/x86"
      armv7:
        image: conanio/gcc8-armv7
        environment:
          - PROFILE="profiles/armv7"

