# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  main_clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"
    
  build:
    stage: "build"
    environment:
      - CONAN_USER_HOME=/codefresh/volume/.conan
    commands:
      - chmod +x build.sh && ./build.sh
    scale:
      x86_64:
        image: conanio/gcc8
        environment:
          - PROFILE=profiles/x86_64
      x86:
        image: conanio/gcc8
        environment:
          - PROFILE=profiles/x86
      # armv7:
      #   image: conanio/gcc8-armv7
      #   environment:
      #     - PROFILE=profiles/armv7
      # armv8:
      #   image: conanio/gcc8-armv8
      #   environment:
      #     - PROFILE=profiles/armv8
  test:
    stage: "test"
    commands:
      - apt update && apt install allure -y
      - cd $GOOGLE_TEST_FOLDER_PATH && ./GoogleTests --gtest_output=xml:report.xml
      - allure generate --profile junit .
    scale:
      test_x86_64:
        image: conanio/gcc8
        environment:
          - GOOGLE_TEST_FOLDER_PATH=build/profiles/x86_64/test/bin
      test_x86:
        image: conanio/gcc8
        environment:
          - GOOGLE_TEST_FOLDER_PATH=build/profiles/x86/test/bin
      # test_armv7:
      #   image: arm32v7/ubuntu
      #   environment:
      #     - GOOGLE_TEST_FOLDER_PATH=build/profiles/armv7/test/bin
      # test_armv8:
      #   image: arm64v8/ubuntu
      #   environment:
      #     - GOOGLE_TEST_FOLDER_PATH=build/profiles/armv8/test/bin
          

